/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const QueueLazyImport = createFileRoute('/queue')()
const CreditsLazyImport = createFileRoute('/credits')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const QueueLazyRoute = QueueLazyImport.update({
  path: '/queue',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/queue.lazy').then((d) => d.Route))

const CreditsLazyRoute = CreditsLazyImport.update({
  path: '/credits',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/credits.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/credits': {
      id: '/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof CreditsLazyImport
      parentRoute: typeof rootRoute
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  CreditsLazyRoute,
  QueueLazyRoute,
})

/* prettier-ignore-end */
